export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const FETCH_COMMENTS = 'COMMENT/FETCH_COMMENTS';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';