export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const GET_PRODUCTS = 'PRODUCT/GET_PRODUCTS';
export const SHOW_PRODUCTS = 'PRODUCT/SHOW_PRODUCTS';