import Box from "@mui/material/Box";
import {myTheme} from "../styles/myTheme";

const Home = () => {
  return (
    <Box sx={{bgcolor: myTheme.light.background.primary, height: "100%"}}>
      Home component

      Lorem ipsum urna, ipsum leo elementum enim amet vitae tellus vitae quisque justo. Et sodales ornare pharetra sed gravida - pellentesque nec: orci sapien pharetra mauris sem nibh, proin lectus ornare gravida mauris massa. Sagittis ipsum ultricies, bibendum massa mattis amet proin mauris congue cursus metus gravida. Diam fusce ultricies et maecenas nec - a, mattis leo vitae malesuada ornare proin commodo sed, quam. Vivamus sapien nulla nibh tellus cursus risus ipsum ultricies proin, lectus eros leo ligula eget orci molestie justo urna ipsum sem. Ultricies commodo odio duis et integer sed metus morbi ultricies justo morbi.

      Tellus sodales nibh curabitur ultricies diam nec metus ut pharetra pellentesque rutrum mattis mauris molestie tempus massa orci. Ultricies vitae sed risus at nibh sit arcu, risus ut, gravida in tellus mauris morbi. Pellentesque porta urna et quisque congue in tempus orci ligula sem metus vitae, bibendum molestie elementum nulla. Magna - fusce ornare, leo ornare, tellus magna proin bibendum, donec integer metus justo: elementum proin malesuada ornare. Leo, nam, ipsum pellentesque ligula eros mattis maecenas at quam quisque maecenas urna, duis: leo lectus sit odio, ipsum, sapien tellus duis quam eget. Molestie proin auctor cursus pellentesque cursus fusce et sagittis et ligula, quisque sapien, diam enim sem, congue integer malesuada rutrum malesuada curabitur.

      Duis nulla proin molestie, adipiscing elementum lectus sodales, diam sed, et porta nulla quam. Ligula, odio porta tempus fusce in diam at - sit quisque ultricies in ut et justo amet quam auctor quam eros sem justo eu. Massa congue sagittis nulla adipiscing sapien duis integer morbi nulla, mauris ut commodo ipsum, donec. At duis et enim, urna fusce morbi - duis eget pellentesque: sagittis, sapien non eu, arcu magna mattis et eros. Vivamus - amet vulputate pharetra ipsum integer, a metus lorem eu tempus a metus tempus ultricies diam - orci enim massa nulla. Quisque arcu mattis metus rutrum in sem quam amet in gravida ut pharetra ligula massa eget vitae, quam risus nulla nam tempus, eros vitae. Sed fusce lorem congue rutrum cursus, mattis nibh elementum tellus diam morbi elementum massa sapien magna nibh, adipiscing integer rutrum metus. Justo risus gravida donec proin arcu eu ornare nec auctor, vivamus commodo tellus proin in.

      At eros tempus sit orci enim sagittis, odio ligula ultricies vivamus porta quisque fusce quam maecenas nec orci, sapien. Integer molestie, metus vitae orci porta ultricies risus at - nam, lorem eu. Amet orci ligula at proin curabitur morbi, sit ligula amet pellentesque tempus malesuada lorem tellus sed ornare maecenas. Tellus sodales leo tellus in quisque in fusce duis ligula donec in rutrum eros ornare pellentesque. Odio mattis, vitae, lectus sit elementum leo nibh pellentesque eros leo pharetra proin. Nec ultricies porttitor non leo vivamus massa eget risus non, molestie proin porta vitae porttitor risus eu nibh magna.

      Ligula adipiscing, duis rutrum porttitor duis enim auctor quam tellus auctor quam adipiscing vitae amet adipiscing mattis. Nibh, at et tempus sagittis integer adipiscing tempus sed: duis mattis morbi sapien in non, elementum molestie in.

      Porta quam: pharetra eros arcu mattis vitae, nibh adipiscing, pellentesque fusce, pellentesque. Sem molestie eget vulputate: tellus diam eros rutrum nam, quam, proin adipiscing morbi risus sapien maecenas, quisque, at sagittis maecenas ipsum vivamus, vulputate porttitor. Maecenas odio nec sit nulla auctor lorem sed diam auctor tellus justo, proin commodo auctor urna risus eget duis, maecenas. Magna ligula risus - arcu metus ligula, curabitur non odio cursus odio curabitur ligula duis adipiscing ut mattis.

      Malesuada amet sed elementum porta mauris eros in: pharetra orci arcu sit. Orci, massa leo quisque ultricies elementum maecenas pharetra eros sit eu, duis tempus. Molestie ornare eget porta donec proin odio diam leo molestie sit gravida, eros. Sapien nec rutrum ornare enim duis sem - sodales orci sit urna ornare eu ligula vitae, cursus vivamus orci massa - quisque. Magna pharetra diam duis non sit mattis vulputate justo odio et sit urna eget congue adipiscing ultricies magna auctor. Morbi tellus gravida at - nam sodales curabitur, quisque ornare adipiscing massa malesuada lectus - bibendum. Odio massa pellentesque rutrum morbi vivamus malesuada lorem nam massa eget.

      Quam nibh eget eu ornare at nec vivamus sodales ornare, nec ipsum proin a malesuada nulla orci auctor fusce enim amet eget. Duis sagittis non ultricies sagittis lorem vitae, auctor diam eget justo. Vitae non eros mattis porttitor nam nibh sit magna elementum nec vitae ornare rutrum sed. Arcu et molestie rutrum sed arcu curabitur nam massa morbi vivamus in eros commodo adipiscing rutrum. Eros elementum maecenas duis, nibh, maecenas, et quam vivamus, vulputate pharetra nibh quisque a ipsum nam molestie sapien non maecenas quam mattis non.

      Sagittis tellus congue tempus integer bibendum metus sagittis amet rutrum, metus risus. Maecenas risus diam nam at risus pharetra sagittis: nam mattis sem elementum arcu sit nam. Proin ornare duis bibendum sapien risus donec duis, urna leo sagittis orci. Lorem - et urna ultricies, vivamus justo mattis nulla pellentesque elementum ornare. Eget malesuada ultricies vivamus ut - adipiscing tempus sed eu metus, ut proin nec at leo arcu ipsum.

      Curabitur tempus adipiscing integer a quam morbi odio urna tempus nec et eu porta auctor. Proin tempus magna at nibh rutrum, tempus sem, metus pharetra bibendum orci lorem leo ut arcu eu non sagittis ornare pellentesque. Metus ornare tellus sed eros commodo bibendum malesuada in non rutrum mattis, tempus non ultricies. Bibendum eros tellus eget mattis porta porttitor nibh risus sit rutrum leo - maecenas adipiscing justo fusce lectus tellus in pellentesque. Et, pharetra rutrum vulputate ipsum quisque magna non et mauris lectus sodales orci tellus vulputate nec sed risus. Lectus nibh sapien nibh non massa ligula ipsum nec, at porttitor porta. Amet mauris nibh, ligula ipsum, vivamus risus rutrum mauris pellentesque, eros magna duis non pharetra enim sodales.

      Lorem ipsum urna, ipsum leo elementum enim amet vitae tellus vitae quisque justo. Et sodales ornare pharetra sed gravida - pellentesque nec: orci sapien pharetra mauris sem nibh, proin lectus ornare gravida mauris massa. Sagittis ipsum ultricies, bibendum massa mattis amet proin mauris congue cursus metus gravida. Diam fusce ultricies et maecenas nec - a, mattis leo vitae malesuada ornare proin commodo sed, quam. Vivamus sapien nulla nibh tellus cursus risus ipsum ultricies proin, lectus eros leo ligula eget orci molestie justo urna ipsum sem. Ultricies commodo odio duis et integer sed metus morbi ultricies justo morbi.

      Tellus sodales nibh curabitur ultricies diam nec metus ut pharetra pellentesque rutrum mattis mauris molestie tempus massa orci. Ultricies vitae sed risus at nibh sit arcu, risus ut, gravida in tellus mauris morbi. Pellentesque porta urna et quisque congue in tempus orci ligula sem metus vitae, bibendum molestie elementum nulla. Magna - fusce ornare, leo ornare, tellus magna proin bibendum, donec integer metus justo: elementum proin malesuada ornare. Leo, nam, ipsum pellentesque ligula eros mattis maecenas at quam quisque maecenas urna, duis: leo lectus sit odio, ipsum, sapien tellus duis quam eget. Molestie proin auctor cursus pellentesque cursus fusce et sagittis et ligula, quisque sapien, diam enim sem, congue integer malesuada rutrum malesuada curabitur.

      Duis nulla proin molestie, adipiscing elementum lectus sodales, diam sed, et porta nulla quam. Ligula, odio porta tempus fusce in diam at - sit quisque ultricies in ut et justo amet quam auctor quam eros sem justo eu. Massa congue sagittis nulla adipiscing sapien duis integer morbi nulla, mauris ut commodo ipsum, donec. At duis et enim, urna fusce morbi - duis eget pellentesque: sagittis, sapien non eu, arcu magna mattis et eros. Vivamus - amet vulputate pharetra ipsum integer, a metus lorem eu tempus a metus tempus ultricies diam - orci enim massa nulla. Quisque arcu mattis metus rutrum in sem quam amet in gravida ut pharetra ligula massa eget vitae, quam risus nulla nam tempus, eros vitae. Sed fusce lorem congue rutrum cursus, mattis nibh elementum tellus diam morbi elementum massa sapien magna nibh, adipiscing integer rutrum metus. Justo risus gravida donec proin arcu eu ornare nec auctor, vivamus commodo tellus proin in.

      At eros tempus sit orci enim sagittis, odio ligula ultricies vivamus porta quisque fusce quam maecenas nec orci, sapien. Integer molestie, metus vitae orci porta ultricies risus at - nam, lorem eu. Amet orci ligula at proin curabitur morbi, sit ligula amet pellentesque tempus malesuada lorem tellus sed ornare maecenas. Tellus sodales leo tellus in quisque in fusce duis ligula donec in rutrum eros ornare pellentesque. Odio mattis, vitae, lectus sit elementum leo nibh pellentesque eros leo pharetra proin. Nec ultricies porttitor non leo vivamus massa eget risus non, molestie proin porta vitae porttitor risus eu nibh magna.

      Ligula adipiscing, duis rutrum porttitor duis enim auctor quam tellus auctor quam adipiscing vitae amet adipiscing mattis. Nibh, at et tempus sagittis integer adipiscing tempus sed: duis mattis morbi sapien in non, elementum molestie in.

      Porta quam: pharetra eros arcu mattis vitae, nibh adipiscing, pellentesque fusce, pellentesque. Sem molestie eget vulputate: tellus diam eros rutrum nam, quam, proin adipiscing morbi risus sapien maecenas, quisque, at sagittis maecenas ipsum vivamus, vulputate porttitor. Maecenas odio nec sit nulla auctor lorem sed diam auctor tellus justo, proin commodo auctor urna risus eget duis, maecenas. Magna ligula risus - arcu metus ligula, curabitur non odio cursus odio curabitur ligula duis adipiscing ut mattis.

      Malesuada amet sed elementum porta mauris eros in: pharetra orci arcu sit. Orci, massa leo quisque ultricies elementum maecenas pharetra eros sit eu, duis tempus. Molestie ornare eget porta donec proin odio diam leo molestie sit gravida, eros. Sapien nec rutrum ornare enim duis sem - sodales orci sit urna ornare eu ligula vitae, cursus vivamus orci massa - quisque. Magna pharetra diam duis non sit mattis vulputate justo odio et sit urna eget congue adipiscing ultricies magna auctor. Morbi tellus gravida at - nam sodales curabitur, quisque ornare adipiscing massa malesuada lectus - bibendum. Odio massa pellentesque rutrum morbi vivamus malesuada lorem nam massa eget.

      Quam nibh eget eu ornare at nec vivamus sodales ornare, nec ipsum proin a malesuada nulla orci auctor fusce enim amet eget. Duis sagittis non ultricies sagittis lorem vitae, auctor diam eget justo. Vitae non eros mattis porttitor nam nibh sit magna elementum nec vitae ornare rutrum sed. Arcu et molestie rutrum sed arcu curabitur nam massa morbi vivamus in eros commodo adipiscing rutrum. Eros elementum maecenas duis, nibh, maecenas, et quam vivamus, vulputate pharetra nibh quisque a ipsum nam molestie sapien non maecenas quam mattis non.

      Sagittis tellus congue tempus integer bibendum metus sagittis amet rutrum, metus risus. Maecenas risus diam nam at risus pharetra sagittis: nam mattis sem elementum arcu sit nam. Proin ornare duis bibendum sapien risus donec duis, urna leo sagittis orci. Lorem - et urna ultricies, vivamus justo mattis nulla pellentesque elementum ornare. Eget malesuada ultricies vivamus ut - adipiscing tempus sed eu metus, ut proin nec at leo arcu ipsum.

      Curabitur tempus adipiscing integer a quam morbi odio urna tempus nec et eu porta auctor. Proin tempus magna at nibh rutrum, tempus sem, metus pharetra bibendum orci lorem leo ut arcu eu non sagittis ornare pellentesque. Metus ornare tellus sed eros commodo bibendum malesuada in non rutrum mattis, tempus non ultricies. Bibendum eros tellus eget mattis porta porttitor nibh risus sit rutrum leo - maecenas adipiscing justo fusce lectus tellus in pellentesque. Et, pharetra rutrum vulputate ipsum quisque magna non et mauris lectus sodales orci tellus vulputate nec sed risus. Lectus nibh sapien nibh non massa ligula ipsum nec, at porttitor porta. Amet mauris nibh, ligula ipsum, vivamus risus rutrum mauris pellentesque, eros magna duis non pharetra enim sodales.


    </Box>
  )
}

export default Home;